/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

/**
 *
 * @author vandita
 */
import java.awt.*;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import java.sql.*;
import javax.swing.*;
import java.util.*;


public class screening extends javax.swing.JFrame {

    /**
     * Creates new form screening
     */
    //JPanel screenpanel;
    //JScrollPane screenscroll;
     //static screening myFrame;
    public static Connection connecrDb() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bms", "root", "password");
            return conn;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("Connection failure");
        }
        return null;
    }
    
    /**
     * Creates new form login
     */
    Connection conn = null;
    ResultSet rs = null;
    ResultSet rs1=null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    HashMap<String,ArrayList> screen=new HashMap <>();
    public screening() {
        initComponents1();
        

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(58, 58, 58)
//                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(100, 100, 100)
//                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
//                .addComponent(Go)
//                .addGap(39, 39, 39))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(16, 16, 16)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(Go))
//                .addContainerGap(282, Short.MAX_VALUE))
//        );
        
        conn = connecrDb();
        //myFrame = new screening();
        
	//set up the buttons scroll pane
	/*screenscroll = new JScrollPane(screenpanel);
	screenscroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
	screenscroll.setPreferredSize(new Dimension(500, 60));
        screenscroll.setViewportView(screenpanel);
        this.rootPane.add(screenscroll); // or other panel etc
	//add stuff to the panel*/
	//this.add(screenpanel, BorderLayout.PAGE_START);
	//this.add(screenscroll, BorderLayout.PAGE_END);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents1(){
        setLayout(new BorderLayout());
        location = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        Go = new javax.swing.JButton();
        //new javax.swing.JScrollPane();
        screenpanel = new JPanel(new FlowLayout());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(1300,1500);
        setLocation(new java.awt.Point(500, 200));
        //setVisible(true);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jaipur", "Noida", "Faridabad", "Gurgaon" }));

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018-10-01", "2018-10-02" }));

        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        getContentPane().add(screenpanel,BorderLayout.CENTER);
        getContentPane().add(location,BorderLayout.LINE_START);
        getContentPane().add(date,BorderLayout.LINE_END);
        getContentPane().add(Go,BorderLayout.PAGE_END);
        pack();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        location = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        Go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(312, 241));
        setResizable(false);

        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jaipur", "Noida", "Faridabad", "Gurgaon" }));

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018-10-01", "2018-10-02" }));

        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(Go)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
                    // TODO add your handling code here:
        Object selectedItemloc = location.getSelectedItem();
        Object selectedItemdate = date.getSelectedItem();
        String loc;
        loc = selectedItemloc.toString();
        String movdate;
        movdate=selectedItemdate.toString();
        String sql = "select cinemahall.chname,time from screening inner join cinemahall on screening.challid=cinemahall.challid where cinemahall.chlocation=? and screening.date=? and screening.movieid=1;";
        //String sql1="select chname from cinemahall where challid=?";
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1,loc);
            pst.setString(2,movdate);
            rs=pst.executeQuery();
            while(rs.next())
            {
                //make a dictionary with challid(chname) as key and list of time as value
                try
                {
                    //System.out.println("hi");
                   // rs1=pst1.executeQuery();
                    String cinemaname=rs.getNString("chname");
                    if (!screen.containsKey(cinemaname))
                    {
                    
                    ArrayList screentime=new ArrayList();
                    screentime.add(rs.getInt("time"));
                    screen.put(cinemaname, screentime);
                    
                    }
                    else
                    {
                        screen.get(cinemaname).add(rs.getInt("time"));
                    }
                    
                }
                catch (Exception ex)
                {
                    //System.out.println("why");
                    JOptionPane.showMessageDialog(null, ex);
                }
                

            }
            /*GridBagConstraints constraint = new GridBagConstraints();
            constraint.anchor = GridBagConstraints.CENTER;
            constraint.fill = GridBagConstraints.NONE;
            constraint.gridx = 0;
            constraint.gridy = GridBagConstraints.RELATIVE;
            constraint.weightx = 1.0f;
            constraint.weighty = 1.0f;*/
            for (String cinemaname : screen.keySet()){
            //  System.out.println(cinemaname+screen.get(cinemaname)+"\n");
            String buttonlabel=cinemaname+screen.get(cinemaname);
            //JButton screeningpagego = new JButton();
           // screeningpagego.setText("hi");
                screenpanel.add(new JButton(buttonlabel));
               // myFrame.pack();
                System.out.println("button forming\n");
                //screenbutton= screentime.add(screeningpage);
                //screentime.add(new subPanel());
                //screenpanel.updateUI();
                screenpanel.revalidate();
                //screenpanel.repaint();
                validate();
                screenpanel.setVisible(true);
                
            } 
            
            

            
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_GoActionPerformed
 
   

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Go;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> location;
    // End of variables declaration//GEN-END:variables
   // private javax.swing.JButton screeningpagego;
    private javax.swing.JPanel screenpanel;
    private javax.swing.JScrollPane screenscroll;

}
